"""add transaction type

Revision ID: 80b6c20eefdf
Revises: cf652e1a0916
Create Date: 2025-12-26 21:32:25.218795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80b6c20eefdf'
down_revision: Union[str, Sequence[str], None] = 'cf652e1a0916'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('type', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'type')
    # ### end Alembic commands ###
